# Generated by Django 5.2.3 on 2025-07-08 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csv_files/')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_signs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signs.sign')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_training', models.FileField(upload_to='csv_training_file/')),
                ('notes', models.CharField(max_length=200)),
                ('id_signs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signs.sign')),
            ],
        ),
    ]
