# Generated by Django 5.2.3 on 2025-07-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signvideos',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
