# Generated by Django 5.2.3 on 2025-07-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0002_signvideos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='signvideos',
            name='ap_re',
            field=models.BooleanField(default=False),
        ),
    ]
