# Generated by Django 5.2.3 on 2025-07-17 16:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0003_signvideos_ap_re'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signvideos',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='videos'),
        ),
    ]
