# Generated by Django 5.2.3 on 2025-07-25 16:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0004_alter_signvideos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodel',
            name='version',
            field=models.CharField(default='1.0', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signvideos',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='trainingmodel',
            name='notes',
            field=models.CharField(max_length=250),
        ),
    ]
