# Generated by Django 5.2.3 on 2025-07-25 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0005_trainingmodel_version_alter_signvideos_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodel',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
