# Generated by Django 5.2.3 on 2025-07-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0006_trainingmodel_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=30)),
            ],
        ),
    ]
