# Generated by Django 5.2.3 on 2025-07-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0008_alter_sign_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signvideos',
            name='id_signs',
        ),
    ]
