# Generated by Django 5.2.3 on 2025-07-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0009_remove_signvideos_id_signs'),
    ]

    operations = [
        migrations.AddField(
            model_name='signvideos',
            name='etiqueta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signs.etiqueta'),
            preserve_default=False,
        ),
    ]
