# Generated by Django 5.2.3 on 2025-07-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0010_signvideos_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='nombre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signs.etiqueta'),
        ),
    ]
