# Generated by Django 5.2.3 on 2025-07-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0011_alter_sign_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='signvideos',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
