# Generated by Django 5.2.3 on 2025-10-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0012_signvideos_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='signvideos',
            name='nombre',
            field=models.CharField(default='-', max_length=25),
            preserve_default=False,
        ),
    ]
